### ISSUE TITLE
[accessibility-alt-text-bot] Support for Discussions

### ISSUE THREAD

**Issue by khiga8** [github/accessibility-alt-text-bot#11]
Currently this action has support for Issues and Pull Requests. Let's add support for Discussions!

- [x] Support for discussion body
- [x] Support for discussion comment
- [x] Cut new release

**Comment by kendallgassner** [comment]
Ah, I see we will need some additional logic to gather the right params.

Reference:
[action.yml line 13](https://github.com/github/accessibility-alt-text-bot/blob/main/action.yml#L13)
