### ISSUE TITLE
Simplify alt-text-bot Workflow

### ISSUE THREAD

**Issue by kendallgassner** [github/accessibility-alt-text-bot#38]
### What

As pointed out in https://github.com/JoshuaKGoldberg/create-typescript-app/issues/997 the if statement in our alt-text-bot workflow is likely unnecessary. 

https://github.com/github/accessibility-alt-text-bot/blob/7932b9072f96703809a75c48c771abf33c3fb39b/.github/workflows/test-accessibility-alt-text-bot.yml#L18

### Acceptance Criteria

- [ ] - Run a test to ensure the `if` statement is not necessary
- [ ] - Remove `if` statement from our ['test' workflow](https://github.com/github/accessibility-alt-text-bot/blob/7932b9072f96703809a75c48c771abf33c3fb39b/.github/workflows/test-accessibility-alt-text-bot.yml)
- [ ] - Remove `if` statement from our readme

**Comment by DerTimonius** [comment]
I created a small repo with the `if` statement removed and [created an issue](https://github.com/DerTimonius/a11y-bot-test/issues/1) where I added an image without an alt text. There was no comment made by the bot, so I guess the `if` is necessary?

**Comment by kendallgassner** [comment]
@DerTimonius I tested this on my end, and it actually just looks like it was due to a [version issue in the README](https://github.com/github/accessibility-alt-text-bot/pull/39). If you bump to 1.4.0 you do not need the `if`.

**Comment by DerTimonius** [comment]
Ah, I see. Thanks for the clarification 🙂

**Comment by kendallgassner** [comment]
Thanks for testing!
